config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  get 'greetings/hello'
  get 'greetings/time'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
  end
  def time
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/greetings/hello.html.erb
<h1>Welcome to the information input system</h1>
<h1> </h1>
<h1> </h1>
<h1> </h1>
<div ><%= link_to("The time", "/greetings/time") %></div>
<div ><%= link_to("To the system", "/visitors") %></div>
<div ><a href="https://github.com/lantu81">To My github</a><div >

app/views/greetings/time.html.erb
<h1>The Time Now</h1>
<div ><script type="text/javascript">
var myDate = new Date();
document.write(myDate.toLocaleString())
setInterval(function(){
    window.location.reload();
},500);


</script></div>
<div ><%= link_to("back", "/greetings/hello") %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  	<body id="body_background">
    <%= yield %>
  </body>
</html>

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :visitor_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :visitor_age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :visitor_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<div ><%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %> </div>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<table align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.name %></td>
        <td><%= visitor.age %></td>
        <td><%= visitor.email %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div ><%= link_to 'New Visitor', new_visitor_path %></div>
<div ><%= link_to("back", "/greetings/hello") %></div>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

 <div><%= link_to 'Back', visitors_path %> </div>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @visitor.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

 <div><%= link_to 'Edit', edit_visitor_path(@visitor) %> |
 <%= link_to 'Back', visitors_path %> </div>